spring.datasource:
  url: jdbc:mysql://localhost:3306/blog?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
  dialect: org.hibernate.dialect.MySQL8Dialect
  username: root
  password: testtest
spring.jpa.hibernate.ddl-auto: create
