spring.datasource:
  url: jdbc:mysql://localhost:3306/blog?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=UTF-8&useLegacyDatetimeCode=false&serverTimezone=UTC
  dialect: org.hibernate.dialect.MySQL8Dialect
  username: root
  password: testtest

spring.jpa:
  hibernate.ddl-auto: validate
  show-sql: true
  properties.hibernate.jdbc.time_zone: UTC

blog:
  title: DevPub
  subtitle: Рассказы разработчиков
  phone: +7 987 654-32-10
  email: blog@nomail.ru
  copyright: Сергей Решетник
  copyrightFrom: 2021
  captchaExpiration: PT1H
