server.port=${PORT:8080}

spring.datasource:
  url: jdbc:${JAWSDB_URL:mysql://localhost:3306/blog?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=UTF-8&useLegacyDatetimeCode=false&serverTimezone=UTC}
  dialect: org.hibernate.dialect.MySQL8Dialect
  username: root
  password: testtest

cloudinary-file-storage-service: true

spring.jpa:
  hibernate.ddl-auto: validate
  show-sql: false
  properties.hibernate.jdbc.time_zone: UTC

spring.servlet.multipart:
  max-file-size: 5MB
  max-request-size: 5MB

blog:
  title: DevPub
  subtitle: Рассказы разработчиков
  phone: +7 987 654-32-10
  email: blog@nomail.ru
  copyright: Сергей Решетник
  copyrightFrom: 2021
  captchaExpiration: PT1H

spring.mail:
  host: smtp.gmail.com
  port: 587
  username: ${SMTP_USER:login user to smtp server}
  password: ${SMTP_PASS:login password to smtp server}
  properties.mail.smtp:
    auth: true
    starttls.enable: true
